theme: jekyll-theme-cayman

# The name of your site (displayed in the header)
name: Vaiyai Ramanan

# A short bio or description (displayed in the header)
description: Weather Blogger

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
# baseurl: "vaiyai-ramanan-blog"
url: https://vaiyai-ramanan-blog.github.io/

# Your disqus username, entering this will enable commenting on posts
disqus: vaiyairamanan
